# Generated by Django 4.0.4 on 2022-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=20)),
                ('shift', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=None, max_length=254)),
                ('complaint', models.TextField()),
            ],
        ),
    ]
